### ISSUE TITLE
Release of more data

### ISSUE THREAD

**Issue by Aditya-Kharosekar** [clef2018-factchecking/clef2018-factchecking#5]
The README says that version 1.0 contains some trial data. When will the rest of the training and test data be released?

**Comment by albarron** [comment]
Hi Aditya,

if you are registered to the lab [1] (or to the google group you can access through [1]), you should have received an email today explaining that the test set will be released tomorrow (Friday 27th).

If you have not registered officially, please do so at [2]. Otherwise, you wont be able to submit your predictions. The registration is about to close. I recommend you to act fast.

[1] http://alt.qcri.org/clef2018-factcheck
[2] http://clef2018-labs-registration.dei.unipd.it/
